= XebiaLabs and AWS

:imagesdir: ../../images

== Getting Started

****
*Requirements:*

* AWS Account
* IAM User with administrative privileges
* AWS CLI
* XebiaLabs trial licenses for https://xebialabs.com/products/xl-release/trial/[XL-Release] and https://xebialabs.com/products/xl-deploy/trial/[XL-Deploy]
****

== Introduction

There are a few ways to run through the examples provided in this guide. These can be run from your local environment, but for simplicity our demonstration will use https://aws.amazon.com/cloud9[AWS Cloud9], a cloud-based integrated development environment (IDE) that lets you write, run, and debug your code with just a browser.

=== AWS Cloud9 Setup

To https://docs.aws.amazon.com/cloud9/latest/user-guide/setup-express.html[begin] using AWS Cloud9 quickly, or to use AWS Cloud9 as the only one in your AWS account, simply https://www.youtube.com/watch?v=WviHsoz8yHk[create an AWS account] if you don't already have one, and then https://docs.aws.amazon.com/cloud9/latest/user-guide/setup-express.html#setup-express-sign-in-ide[sign in to the AWS Cloud9 console] with the credentials of the AWS account root user. Next, https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment.html[create an AWS Cloud9 development environment], and then use the AWS Cloud9 IDE to work with code in your new environment. 

=== Update and install some tools.
Now that you have provisioned and setup your Cloud9 IDE, we will need to update the `AWS CLI` and `pip`.
[source,shell]
----
sudo yum update -y && pip install --upgrade --user awscli pip
exec $SHELL
----

=== Configure the AWS Environment
After you have the installed the latest `awscli` and `pip` we need to configure
our environment a little
[source,shell]
----
aws configure set region us-west-2
----

Note: You may substitute the region accordingly.

=== Clone the source repository for this workshop.
Now we want to clone the repository that contains all the content and files you need to complete this workshop.
[source,shell]
----
cd ~/environment
git clone https://github.com/xebialabs/AWSWebinar.git
----

Note: You can open a new `terminal` by pressing the combination keys `alt+t`

****
Please proceed to `./modules/container-registry` when finished.
****